### ISSUE TITLE
The table "{{core_website}}" for active record class "Mage1Website" cannot be found in the database

### ISSUE THREAD

**Issue by CharanjeetE** [ubertheme/magento2_data_migration#63]
I am migrating magento 1.9.3.7 to magento 2.3.0 but getting this error. Please suggest me how can I overcome this issue. I am not using any database prefixes in both m1 or m2.
CDbException
#0 | +  /var/www/m2.gocleaning.nl/pub/ub-tool/yii/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Mage1Website)
-- | --
#1 | +  /var/www/m2.gocleaning.nl/pub/ub-tool/yii/db/ar/CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 | +  /var/www/m2.gocleaning.nl/pub/ub-tool/yii/db/ar/CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 | +  /var/www/m2.gocleaning.nl/pub/ub-tool/yii/db/ar/CActiveRecord.php(1475): CActiveRecord->query(CDbCriteria, true)
#4 | –  /var/www/m2.gocleaning.nl/pub/ub-tool/protected/controllers/MigrateController.php(217): CActiveRecord->findAll("code <> 'admin'")212             //variables to log 213             $migrated_website_ids = $migrated_store_group_ids = $migrated_store_ids = array(); 214  215             //get list front-end websites from magento1 and exclude the admin website 216             $condition = "code <> 'admin'"; 217             $websites = Mage1Website::model()->findAll($condition); 218  219             if (Yii::app()->request->isPostRequest && $step->status == MigrateSteps::STATUS_NOT_DONE) { 220  221                 //un-check foreign key 222                 Yii::app()->mage2->createCommand("SET FOREIGN_KEY_CHECKS=0")->execute();
#5 | +  /var/www/m2.gocleaning.nl/pub/ub-tool/yii/web/actions/CInlineAction.php(49): MigrateController->actionStep2()
#6 | +  /var/www/m2.gocleaning.nl/pub/ub-tool/yii/web/CController.php(308): CInlineAction->runWithParams(array())
#7 | +  /var/www/m2.gocleaning.nl/pub/ub-tool/yii/web/CController.php(286): CController->runAction(CInlineAction)
#8 | +  /var/www/m2.gocleaning.nl/pub/ub-tool/yii/web/CController.php(265): CController->runActionWithFilters(CInlineAction, array())
#9 | +  /var/www/m2.gocleaning.nl/pub/ub-tool/yii/web/CWebApplication.php(282): CController->run("step2")
#10 | +  /var/www/m2.gocleaning.nl/pub/ub-tool/yii/web/CWebApplication.php(141): CWebApplication->runController("migrate/step2")
#11 | +  /var/www/m2.gocleaning.nl/pub/ub-tool/yii/base/CApplication.php(184): CWebApplication->processRequest()
#12 | –  /var/www/m2.gocleaning.nl/pub/ub-tool/index.php(13): CApplication->run()08 // change the following paths if necessary 09 $yii=dirname(__FILE__).'/yii/yii.php'; 10 $config=dirname(__FILE__).'/protected/config/main.php'; 11  12 require_once($yii); 13 Yii::createWebApplication($config)->run();

**Comment by UberthemeTeam** [comment]
Hi @CharanjeetE , 

It's pity that we no longer maintain the outdated script here at Github, and replaced it with a newer [Pro version](https://www.ubertheme.com/magento-extensions-2-x/magento-2-data-migration-pro/). 

Meanwhile, we've just replied to you via the ticket you submitted at Ubertheme [here](https://www.ubertheme.com/question/the-table-core_website-for-active-record-cla-4/). Please follow up further with us there.

Regards,
Ubertheme team
